---
ios_provider:
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  host: "{{ inventory_hostname }}"

snmp:
  trap_source: GigabitEthernet0/0
  server_host: 10.244.10.30
  ast_subnets: 
    - 10.243.10.0 255.255.255.0
    - 10.244.10.0 255.255.255.0
  ast_wildmasks:
    - 10.243.10.0 0.0.0.255
    - 10.244.10.0 0.0.0.255
  
  ro_commstring:
    - 'jinja2ro'
  rw_commstring:
    - jinja2rw3