---
- name: Save Configurations (IOS)
  hosts: border_switches
  gather_facts: no
  connection: local
  vars:
    creds:
      #host: "{{ inventory_hostname }}"
      #username: "ntc"
      #password: "********"
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      #transport: "cli"
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands:
          - show int status
          - show ip route

      register: show_output

    - debug:
        var: show_output

    - template:
        src: "cmd_out.j2"
        #dest: '/tmp/show_commands.txt'
        dest: "./output_ios/show_output_{{ inventory_hostname }}.txt"
