---
# cd /etc/ansible/ine_examples
# ansible-playbook -i hosts_ios output_ios.yml

- name: Save Configurations (IOS)
  hosts: inet_routers
  vars:
    creds:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands: show run 
      register: show_run

    - debug:
        msg: "{{ show_run.stdout[0] }}" 


    - copy:
        content: "{{ show_run.stdout[0] }}"
        dest: "./output_ios/show_run_{{ inventory_hostname }}.txt"         