---
- name: Audit current device configuration
  hosts: routers
  gather_facts: no
  connection: local
  vars:
    creds:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands:
          - show version
          - show ip int brief

      register: show_output

    - debug:
        var: show_output

    - template:
        src: "cmd_out.j2"
        #dest: '/tmp/show_commands.txt'
        #dest: "./output_ios/show_output_{{ inventory_hostname }}.txt"
        dest: "./show_output_{{ inventory_hostname }}.txt"
