---
- name: Save Configurations (IOS)
  hosts: dmz_switches
  gather_facts: no
  connection: local
  vars:
    creds:
      #host: "{{ inventory_hostname }}"
      #username: "ntc"
      #password: "********"
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      #transport: "cli"
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands:
          - show run
          - tclsh
          - foreach VAR {
          - 10.128.4.1
          - 10.160.4.1
          - 10.129.4.1
          - 10.132.4.1
          - 10.134.4.1
          - 10.136.4.1
          - 10.138.4.1
          - 10.164.4.1
          - 10.165.4.1
          - 10.170.4.1
          - 10.172.4.1
          - 10.174.4.1
          - 10.176.4.1
          - 10.178.4.1
          - 10.192.64.1 } { ping $VAR source vl4 re 10 }
          - tclquit
          
      register: show_output

    - debug:
        var: show_output

    - template:
        src: "cmd_out.j2"
        #dest: '/tmp/show_commands.txt'
        dest: "./output_gafg/show_output_{{ inventory_hostname }}.txt"
