---
- name: Save Configurations (IOS)
  hosts: core_switches_branches
  gather_facts: no
  connection: local
  vars:
    provider:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      #transport: "cli"

    tasks:
      ios_ping:
        provider: "{{ provider }}"
        dest: 10.132.4.1 
      
    #- name: Test reachability to All Devices from VLAN4
    #  ios_ping:
    #    provider: "{{ provider }}"
    #    dest: 10.134.4.1
    #    source: vlan4
    #    count: 10  
    #  #register: show_output   

    #- debug:
        #var: show_output

    #- template:
        #src: "cmd_out.j2"
        #dest: "./output_gafg/show_output_{{ inventory_hostname }}.txt"


    #- debug:
        #msg: "{{ show_output.stdout[0] }}" 


    #- copy:
        #content: "{{ show_output.stdout[0] }}"
        #dest: "./output_gafg/show_output_{{ inventory_hostname }}.txt"  


